name: Deploy

on:
  workflow_dispatch:
    inputs:
     target_env:
       description: 'The environment to deploy to'
       type: environment
       required: true
         
jobs:
  deploy:
    name: 'Deploy to ${{ github.events.inputs.target_env }}'
  
    runs-on: ubuntu-latest
    
    environment:
      name: ${{ github.events.inputs.target_env }}
      
    steps:
    - uses: actions/checkout@v2
  
    - run: |
        echo Deployment completed!
  
